
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alancontreras
 */
public class VentanaCurp extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCurp
     */
    public VentanaCurp() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Generación de Curp para Mexicanos");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAPaterno = new javax.swing.JTextField();
        txtAMaterno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tbtnSi = new javax.swing.JToggleButton();
        cmbMes = new javax.swing.JComboBox<>();
        tbtnNo = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbtnMasc = new javax.swing.JRadioButton();
        rbtnFem = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        lblNac = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        btnGenerar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        cmbDia = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCurp = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Apellido Paterno:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido Materno:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        txtAPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAPaternoKeyReleased(evt);
            }
        });
        getContentPane().add(txtAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 274, -1));

        txtAMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAMaternoKeyReleased(evt);
            }
        });
        getContentPane().add(txtAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 274, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre (s):");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 274, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha de Nacimiento:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        buttonGroup2.add(tbtnSi);
        tbtnSi.setText("Sí");
        tbtnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnSiActionPerformed(evt);
            }
        });
        getContentPane().add(tbtnSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));

        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        getContentPane().add(cmbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 100, -1));

        buttonGroup2.add(tbtnNo);
        tbtnNo.setText("No");
        tbtnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnNoActionPerformed(evt);
            }
        });
        getContentPane().add(tbtnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("¿Nacido en el extranjero?:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("/");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("/");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, -1, -1));

        buttonGroup1.add(rbtnMasc);
        rbtnMasc.setForeground(new java.awt.Color(255, 255, 255));
        rbtnMasc.setText("Hombre");
        getContentPane().add(rbtnMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        buttonGroup1.add(rbtnFem);
        rbtnFem.setForeground(new java.awt.Color(255, 255, 255));
        rbtnFem.setText("Mujer");
        getContentPane().add(rbtnFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CURP GENERADO:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        lblNac.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblNac.setForeground(new java.awt.Color(255, 255, 255));
        lblNac.setText("Lugar de Nacimiento:");
        lblNac.setEnabled(false);
        getContentPane().add(lblNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Un Estado...", "Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Coahuila", "Colima", "Durango", "Estado de México", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas" }));
        cmbEstado.setEnabled(false);
        getContentPane().add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 200, -1));

        btnGenerar.setBackground(new java.awt.Color(255, 255, 255));
        btnGenerar.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, 30));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, -1, -1));

        cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cmbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 60, -1));

        jLabel10.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("GENERADOR DE CURP MX");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 850, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-mexico-48.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        txtCurp.setEditable(false);
        txtCurp.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtCurp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurpActionPerformed(evt);
            }
        });
        getContentPane().add(txtCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 390, 40));
        getContentPane().add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 80, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Selecciona tu Sexo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logogobmx.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel14.setFont(new java.awt.Font("Noto Nastaliq Urdu", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("continuación:                                NOTA: También contempla a gente nacida en el extranjero.");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel16.setFont(new java.awt.Font("AppleGothic", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Programa elaborado por : Alan Martin Barocio Contreras");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, -1));

        jLabel15.setFont(new java.awt.Font("Noto Nastaliq Urdu", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("Este programa genera la curp a través de los datos proporcionados. El usuario debe ingresar los datos que se piden a");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_Final.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtAPaterno.setText("");
        txtAMaterno.setText("");
        txtNombre.setText("");
        cmbDia.setSelectedIndex(0);
        cmbMes.setSelectedIndex(0);
        txtAño.setText("");
        tbtnSi.setSelected(false);
        tbtnNo.setSelected(false);
        rbtnMasc.setSelected(false);
        rbtnFem.setSelected(false);
        lblNac.setEnabled(false);
        cmbEstado.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tbtnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnSiActionPerformed
        lblNac.setEnabled(false);
        cmbEstado.setEnabled(false);
        
    }//GEN-LAST:event_tbtnSiActionPerformed

    private void tbtnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnNoActionPerformed
        lblNac.setEnabled(true);
        cmbEstado.setEnabled(true);
    }//GEN-LAST:event_tbtnNoActionPerformed

    private void txtCurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurpActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        if (txtAPaterno.getText().equals("")) {
            showMessageDialog(null, "Ingresa el apellido paterno");
        } else if (txtAMaterno.getText().equals("")) {
            showMessageDialog(null, "Ingresa el apellido Materno");
        } else if (txtNombre.getText().equals("")) {
            showMessageDialog(null, "Ingresa tu nombre o nombres");
        } else{
            generaCurp();
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void txtAPaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAPaternoKeyReleased
        int pos = txtAPaterno.getCaretPosition();
        txtAPaterno.setText(txtAPaterno.getText().toUpperCase());
        txtAPaterno.setCaretPosition(pos);
    }//GEN-LAST:event_txtAPaternoKeyReleased

    private void txtAMaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAMaternoKeyReleased
        int pos = txtAMaterno.getCaretPosition();
        txtAMaterno.setText(txtAMaterno.getText().toUpperCase());
        txtAMaterno.setCaretPosition(pos);
    }//GEN-LAST:event_txtAMaternoKeyReleased

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        int pos = txtNombre.getCaretPosition();
        txtNombre.setText(txtNombre.getText().toUpperCase());
        txtNombre.setCaretPosition(pos);
    }//GEN-LAST:event_txtNombreKeyReleased

    
    
    
    public void generaCurp(){
        char c1 = txtAPaterno.getText().charAt(0);
        char c2 = 0;
        for (int i = 1; i < txtAPaterno.getText().length(); i++) {
            char l = txtAPaterno.getText().charAt(i);
            if(l == 'A' || l == 'E' || l == 'I' || l == 'O' || l == 'U'){
                c2 = l;
                break;
            }
        }
        char c3 = txtAMaterno.getText().charAt(0);
        char c4 = txtNombre.getText().charAt(0);
        
        char c5 = txtAño.getText().charAt(2);
        char c6 = txtAño.getText().charAt(3);
        char c7 = 0;
        char c8 = 0;
        
        switch (cmbMes.getSelectedIndex()){
            case 0:
                c7 = 0;
                c8 = 1;
                break;
            case 1:
                c7 = 0;
                c8 = 2;
                break;
            case 2:
                c7 = 0;
                c8 = 3;
                break;
            case 3:
                c7 = 0;
                c8 = 4;
                break;
            case 4:
                c7 = 0;
                c8 = 5;
                break;
            case 5:
                c7 = 0;
                c8 = 6;
                break;
            case 6:
                c7 = 0;
                c8 = 7;
                break;
            case 7:
                c7 = 0;
                c8 = 8;
                break;
            case 8:
                c7 = 0;
                c8 = 9;
                break;
            case 9:
                c7 = 1;
                c8 = 0;
                break;
            case 10:
                c7 = 1;
                c8 = 1;
                break;
            case 11:
                c7 = 1;
                c8 = 2;
                break;
        }
        
        char c9 = 0;
        char c10 = 0;
                
        if(cmbDia.getSelectedIndex() < 9){
            c9 = '0';
            c10 = cmbDia.getSelectedItem().toString().charAt(0);
        }else if(cmbDia.getSelectedIndex() > 9 && cmbDia.getSelectedIndex() < 19){
            c9 = '1';
            c10 = cmbDia.getSelectedItem().toString().charAt(1);
        }
        
        char c11 = 0;
        if (rbtnMasc.isSelected()) {
            c11 = 'H';
        }else if(rbtnFem.isSelected()){
            c11 = 'F';
        }
        
        char c12 = 0;
        char c13 = 0;
        if (tbtnSi.isSelected()) {
            c12 = 'N';
            c13 = 'E';
        }else{
        switch(cmbEstado.getSelectedIndex()){
        case 0:
            showMessageDialog(null,"TIENES QUE ELEGIR TU LUGAR DE NACIMIENTO.");
            return;
        case 1:
            c12='A';
            c13='S';
            break;
         
        case 2:
            c12='B';
            c13='C';
            break;
            
        case 3:
            c12='B';
            c13='S';
            
            break;

        case 4:
            c12='C';
            c13='C';
            break;
        
        case 5:
            c12='C';
            c13='L';
            break;
            
        case 6:
            c12='C';
            c13='M';
            break;

        case 7:
            c12='C';
            c13='S';
            break;

        case 8:
            c12='C';
            c13='H';
            break;

        case 9:
            c12='D';
            c13='G';
            break;

        case 10:
            c12='G';
            c13='T';
            break;

        case 11:
            c12='G';
            c13='R';
            break;

        case 12:
            c12='H';
            c13='G';
            break;
            
        case 13:
            c12='J';
            c13='C';
            break;

        case 14:
            c12='M';
            c13='C';
            break;

        case 15:
            c12='M';
            c13='N';
            break;

        case 16:
            c12='M';
            c13='S';
            break;

        case 17:
            c12='N';
            c13='T';
            break;

        case 18:
            c12='N';
            c13='L';
            break;

        case 19:
            c12='O';
            c13='C';
            break;

        case 20:
            c12='P';
            c13='L';
            break;
            
        case 21:
            c12='Q';
            c13='T';
            break;
            
        case 22:
            c12='Q';
            c13='R';
            break;

        case 23:
            c12='S';
            c13='P';
            break;

        case 24:
            c12='S';
            c13='L';
            break;

        case 25:
            c12='S';
            c13='R';
            break;

        case 26:
            c12='T';
            c13='C';
            break;

        case 27:
            c12='T';
            c13='S';
            break;
        case 28:
            c12='T';
            c13='L';
            break;

        case 29:
            c12='V';
            c13='Z';
            break;
        
        case 30:
            c12='Y';
            c13='N';
            break;
                 
        case 31:    
            c12='Z';
            c13='S';
            break;         
         }
        }
        
        char c14 = 0;
        
        for (int i = 1; i < txtAPaterno.getText().length(); i++) {
            char l = txtAPaterno.getText().charAt(i);
            if(l != 'A' && l != 'E' && l != 'I' && l != 'O' && l != 'U'){
                c14 = l;
                break;
            }
        }
        
        char c15 = 0;
        
        for (int i = 1; i < txtAMaterno.getText().length(); i++) {
            char l = txtAMaterno.getText().charAt(i);
            if(l != 'A' && l != 'E' && l != 'I' && l != 'O' && l != 'U'){
                c15 = l;
                break;
            }
        }
        
        char c16 = 0;
        
        for (int i = 1; i < txtNombre.getText().length(); i++) {
            char l = txtNombre.getText().charAt(i);
            if(l != 'A' && l != 'E' && l != 'I' && l != 'O' && l != 'U'){ 
                c16 = l;
                break;
            }
        }
        
        curpg = String.valueOf(c1+""+c2+""+c3+""+c4+""+c5+""+c6+""+c7+""+c8+""+c9+""+c10+""+c11+""+c12+""+c13+""+c14+""+c15+""+c16+"");
        
        txtCurp.setText(curpg);
        JOptionPane.showMessageDialog(null, "Verifica que los datos sean correctos y corrígelos. \n CURP GENERADA: "+curpg);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCurp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCurp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCurp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCurp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCurp().setVisible(true);
            }
        });
    }

    
    public String curpg = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbDia;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblNac;
    private javax.swing.JRadioButton rbtnFem;
    private javax.swing.JRadioButton rbtnMasc;
    private javax.swing.JToggleButton tbtnNo;
    private javax.swing.JToggleButton tbtnSi;
    private javax.swing.JTextField txtAMaterno;
    private javax.swing.JTextField txtAPaterno;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
